name: image_crop_example
description: Demonstrates how to use the image_crop plugin.
repository: https://github.com/holybricks/country-list-pick.git

version: 1.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  image_crop:
    path: ../

flutter:
  uses-material-design: true
